<article>
	<form action="form_cadastro_pet.php" method="post"> 
		<fieldset>
			<legend> Cadastro de Pet </legend>

			<p>
				<label> Espécie: </label>
				<input type="text" nome="especie">
				<label> Nome: </label>
				<input type="text" nome="nome">
				<label> Idade: </label>
				<input type="number" nome="idade">
				<label> Sexo: </label>
				<input type="text" nome="sexo">
			</p>
			
			<input type="submit" value="Cadastrar"> 


		</fieldset>

	</form>


</article>